"""empty message

Revision ID: 629cf4579629
Revises: None
Create Date: 2016-03-29 14:44:42.617879

"""

# revision identifiers, used by Alembic.
revision = '629cf4579629'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mac_id', sa.String(), nullable=False),
    sa.Column('date_captured', sa.DateTime(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('gyro_x', sa.SmallInteger(), nullable=True),
    sa.Column('gyro_y', sa.SmallInteger(), nullable=True),
    sa.Column('gyro_z', sa.SmallInteger(), nullable=True),
    sa.Column('accel_x', sa.SmallInteger(), nullable=True),
    sa.Column('accel_y', sa.SmallInteger(), nullable=True),
    sa.Column('accel_z', sa.SmallInteger(), nullable=True),
    sa.Column('force_1', sa.SmallInteger(), nullable=True),
    sa.Column('force_2', sa.SmallInteger(), nullable=True),
    sa.Column('force_3', sa.SmallInteger(), nullable=True),
    sa.Column('force_4', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_date_captured'), 'record', ['date_captured'], unique=False)
    op.create_index(op.f('ix_record_mac_id'), 'record', ['mac_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_mac_id'), table_name='record')
    op.drop_index(op.f('ix_record_date_captured'), table_name='record')
    op.drop_table('record')
    ### end Alembic commands ###
